server:
  port: 8000

spring:
  profiles:
    active:
  # 服务模块
  devtools:
    restart:
      # 热部署开关
      enabled: true
  datasource:
    druid:
      url: jdbc:mysql://localhost:3306/dbthings?useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=true&serverTimezone=GMT%2B8
      db-type: com.alibaba.druid.pool.DruidDataSource
      password: 123456
      username: root
      driver-class-name: com.mysql.cj.jdbc.Driver
  redis:
    host: 127.0.0.1
    password:
    port: 6379
    timeout: 5s

#  datasource:
#    username: root
#    password: 123456
#    url: jdbc:mysql://localhost:3306/dbthings?useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=true&serverTimezone=GMT%2B8

mybatis:
  #  搜索包名
  mapper-locations: classpath:mybatis/mapper/*.xml
  config-location: classpath:mybatis/mybatis-config.xml
  type-aliases-package: com.jinyuan.domian
#日志
logging:
  level:
    com.jinyuan.schooltrade: debug
    org.springframework: warn

debug: false
